language: node_js
node_js:
  - "10"
script:
  - npm run lint
  - npm run test
  - cat coverage/lcov.info | coveralls
  - npm run build:esdoc
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: "./build/docs"
  on:
    branch: master
cache: npm